kotlin.code.style=official
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true

org.gradle.jvmargs=--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED -Xmx1g -Dfile.encoding=UTF-8

versionOfToolchainsFoojayResolver=1.0.0

documentation.folder=docs

group=me.rdd13r.funtoys

version=1.0.0
